version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: vidma-sa
      POSTGRES_PASSWORD: surething!
      POSTGRES_DB: videomatic
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
